server:
  port: 8902
spring:
  application:
    name: microservice.gateway.zuul
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
security:
  oauth2:
    client:
      accessTokenUri: http://localhost:8902/microservice.auth.service/oauth/token
      userAuthorizationUri: http://localhost:8902/microservice.auth.service/oauth/authorize
      clientAuthenticationScheme: form
    resource:
      user-info-uri: http://localhost:8902/microservice.auth.service/user
      prefer-token-info: false
logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
---
spring:
  profiles: container
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-eureka:8761/eureka/
