server:
  port: 8989
spring:
  application:
    name: microservice.auth.service
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
  datasource:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/msorder?createDatabaseIfNotExist=true&useUnicode=true&autoReconnect=true
    username: msecom
    password: msecom
security:
  oauth2:
    resource:
      filter-order: 3
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.springframework.security: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    org.springframework.cloud.sleuth: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream, info, health

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

---
spring:
  profiles: container
server:
  port: 8202
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-eureka:8761/eureka/

---
spring:
  profiles: container
  jpa:
    show-sql: true
  datasource:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?useSSL=false
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
